version: '3.8'

services:
  web-backend:
    build:
      context: ./web-backend
    container_name: web-backend
    restart: unless-stopped
    volumes:
      - ./web-backend:/var/www
    networks:
      - app-network

  web-frontend:
    build:
      context: ./web-frontend
    container_name: web-frontend
    restart: unless-stopped
    volumes:
      - ./web-frontend:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web-backend:/var/www
    depends_on:
      - web-backend
      - web-frontend
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: